### PR TITLE
Create strings.xml

### PR DESCRIPTION
**Pull request by Seb02859**

### CODE REVIEW

**Comment by varund7726** [comment]
Your XML file is not valid
Please check your syntax by validating your XML file a
thttp://www.w3schools.com/xml/xml_validator.asp

Otherwise build will fail

**Comment by Seb02859** [comment]
It's strange, the xml validator say to me : No errors found....

**Comment by varund7726** [comment]
I'll check again

**Comment by varund7726** [comment]
ok merging

**Pull request merged**
